"""
Naukri scraper.

Naukri's internal search API (https://www.naukri.com/jobapi/v3/search) requires
a header called "nkparam" plus a session cookie, both generated by the browser
and tied to that browsing session - they WILL expire (likely within a day or
two), unlike BigBasket's cookies which kept working unauthenticated for a long
stretch. When this stops working, redo the DevTools capture (see README) and
update the NAUKRI_NKPARAM / NAUKRI_COOKIE values below.

These are read from environment variables rather than hardcoded here, so they
don't end up committed to your GitHub repo:
    NAUKRI_NKPARAM  - the "nkparam" request header value
    NAUKRI_COOKIE   - the full "cookie" request header value
Set these locally before running, and as GitHub Actions secrets for automation.
"""

import os

import requests

SEARCH_URL = "https://www.naukri.com/jobapi/v3/search"

NKPARAM = os.environ.get("NAUKRI_NKPARAM")
COOKIE = os.environ.get("NAUKRI_COOKIE")

BASE_HEADERS = {
    "accept": "application/json",
    "appid": "109",
    "clientid": "d3skt0p",
    "content-type": "application/json",
    "gid": "LOCATION,INDUSTRY,EDUCATION,FAREA_ROLE",
    "systemid": "Naukri",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36",
}


def fetch_naukri_jobs(keyword: str, location: str = "bengaluru", limit: int = 20):
    if not NKPARAM:
        print("[naukri] skipped - NAUKRI_NKPARAM env var not set, see module docstring")
        return []

    headers = dict(BASE_HEADERS)
    headers["nkparam"] = NKPARAM
    if COOKIE:
        headers["cookie"] = COOKIE

    keyword_slug = keyword.replace(" ", "-")
    location_slug = location.replace(" ", "-")

    params = {
        "noOfResults": limit,
        "urlType": "search_by_key_loc",
        "searchType": "adv",
        "keyword": keyword,
        "location": location,
        "pageNo": 1,
        "seoKey": f"{keyword_slug}-jobs-in-{location_slug}".lower(),
        "src": "directSearch",
        "latLong": "",
    }

    try:
        resp = requests.get(SEARCH_URL, params=params, headers=headers, timeout=20)
        resp.raise_for_status()
    except requests.RequestException as e:
        print(f"[naukri] request failed: {e}")
        return []

    try:
        data = resp.json()
    except ValueError:
        print("[naukri] response wasn't JSON - session likely expired, recapture headers")
        return []

    jobs = []
    for item in data.get("jobDetails", []):
        # placeholders is a list of {"type": "location"/"experience"/..., "label": "..."}
        placeholders = {p.get("type"): p.get("label") for p in item.get("placeholders", [])}
        jd_url = item.get("jdURL") or item.get("staticUrl") or ""
        if jd_url and not jd_url.startswith("http"):
            jd_url = "https://www.naukri.com" + jd_url

        jobs.append({
            "id": f"naukri:{item.get('jobId')}",
            "title": item.get("title") or item.get("designation", ""),
            "company": item.get("companyName", ""),
            "location": placeholders.get("location", ""),
            "url": jd_url,
        })
    return jobs
